### ISSUE TITLE
cell line `passages`

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#179] opened 2018-09-07 12:35 UTC
A cell line can have different `passages` ( given an original cell line, grow more in a dish, label that dish a passage - since any biological growth process can introduce variants)

COSMIC has a cell line id see COSS1287381  https://cancer.sanger.ac.uk/cell_lines/sample/overview?id=1287381

**Comment by adamstruck** [comment] 2018-09-07 16:26
I think `passage` can be captured as a property of the `Biosample` or `Aliquot` if it is available.

**Comment by adamstruck** [comment] 2018-11-05 21:43
Duplicate of #176

**Closed by adamstruck** 2018-11-05 21:43 UTC
Labels: enhancement
